package com.word.chain.domain;

public class WordsCtrlCV {

  <1>
  words.add("airplane");
  words.add("banana");
  words.add("cover");
  words.add("draw");
  words.add("express");
  words.add("fall");
  words.add("get");
  words.add("hold");
  words.add("issue");
  words.add("judge");
  words.add("keep");
  words.add("lose");
  words.add("make");
  words.add("note");
  words.add("open");
  words.add("place");
  words.add("quality");
  words.add("run");
  words.add("set");
  words.add("take");
  words.add("upset");
  words.add("value");
  words.add("work");
  words.add("xray,");
  words.add("yet");
  words.add("zone");

  <2>
  words.add("advance");
  words.add("bad");
  words.add("charge");
  words.add("drive");
  words.add("exercise");
  words.add("feel");
  words.add("good");
  words.add("hurt");
  words.add("indicate");
  words.add("just");
  words.add("know");
  words.add("leave");
  words.add("mean");
  words.add("notice");
  words.add("offer");
  words.add("present");
  words.add("quiet");
  words.add("rise");
  words.add("strike");
  words.add("then");
  words.add("urge");
  words.add("vary");
  words.add("wear");
  words.add("xmas");
  words.add("yield");
  words.add("zero");

  <3>
  words.add("ask");
  words.add("bed");
  words.add("change");
  words.add("direct");
  words.add("even");
  words.add("find");
  words.add("go");
  words.add("hit");
  words.add("interest");
  words.add("jealous");
  words.add("keen");
  words.add("late");
  words.add("mind");
  words.add("nervous");
  words.add("operate");
  words.add("plant");
  words.add("quote");
  words.add("right");
  words.add("stretch");
  words.add("treat");
  words.add("upon");
  words.add("view");
  words.add("wonder");
  words.add("xenophobia");
  words.add("year");
  words.add("zoo");

  <4>
  words.add("adopt");
  words.add("box");
  words.add("carry");
  words.add("draft");
  words.add("extend");
  words.add("fancy");
  words.add("grow");
  words.add("hard");
  words.add("introduce");
  words.add("join");
  words.add("kind");
  words.add("light");
  words.add("measure");
  words.add("name");
  words.add("opposite");
  words.add("positive");
  words.add("question");
  words.add("raise");
  words.add("spot");
  words.add("there");
  words.add("unless");
  words.add("visit");
  words.add("whatever");
  words.add("xenon");
  words.add("yawn");
  words.add("zoom");

  <5>
  words.add("appeal");
  words.add("bear");
  words.add("credit");
  words.add("degree");
  words.add("executive");
  words.add("figure");
  words.add("general");
  words.add("hang");
  words.add("impose");
  words.add("journey");
  words.add("key");
  words.add("lay");
  words.add("matter");
  words.add("need");
  words.add("observe");
  words.add("please");
  words.add("quit");
  words.add("range");
  words.add("state");
  words.add("travel");
  words.add("unique");
  words.add("vision");
  words.add("withdraw");
  words.add("xylem");
  words.add("youth");
  words.add("zip");

  <6>
  words.add("accept");
  words.add("bother");
  words.add("condition");
  words.add("develop");
  words.add("experience");
  words.add("feature");
  words.add("give");
  words.add("head");
  words.add("instruction");
  words.add("justice");
  words.add("knit");
  words.add("like");
  words.add("mark");
  words.add("nation");
  words.add("occation");
  words.add("prompt");
  words.add("quarter");
  words.add("report");
  words.add("service");
  words.add("twelve");
  words.add("use");
  words.add("vehicle");
  words.add("well");
  words.add("xml");
  words.add("yellow");
  words.add("zodiac");

  <7>
  words.add("address");
  words.add("beer");
  words.add("cost");
  words.add("due");
  words.add("establish");
  words.add("fiction");
  words.add("gather");
  words.add("hear");
  words.add("intend");
  words.add("junior");
  words.add("kid");
  words.add("look");
  words.add("mess");
  words.add("negative");
  words.add("order");
  words.add("practice");
  words.add("queen");
  words.add("release");
  words.add("should");
  words.add("track");
  words.add("unit");
  words.add("virtue");
  words.add("water");
  words.add("xfactor");
  words.add("yard");
  words.add("zealous");

  <8>
  words.add("against");
  words.add("become");
  words.add("claim");
  words.add("discipline");
  words.add("exhibit");
  words.add("funtion");
  words.add("genius");
  words.add("happen");
  words.add("increase");
  words.add("joy");
  words.add("knot");
  words.add("load");
  words.add("miss");
  words.add("nature");
  words.add("often");
  words.add("play");
  words.add("quickly");
  words.add("reason");
  words.add("subject");
  words.add("talk");
  words.add("usual");
  words.add("very");
  words.add("word");
  words.add("xenodochium");
  words.add("yes");
  words.add("zest");

  <9>
  words.add("account");
  words.add("board");
  words.add("claer");
  words.add("drop");
  words.add("ever");
  words.add("fit");
  words.add("garage");
  words.add("hardly");
  words.add("indeed");
  words.add("jump");
  words.add("kick");
  words.add("level");
  words.add("master");
  words.add("nerveous");
  words.add("occur");
  words.add("promise");
  words.add("query");
  words.add("result");
  words.add("sense");
  words.add("thread");
  words.add("urgent");
  words.add("vote");
  words.add("worth");
  words.add("xylogen");
  words.add("yell");
  words.add("zenith");

  <10>
  words.add("approach");
  words.add("buy");
  words.add("contack");
  words.add("decide");
  words.add("ego");
  words.add("foot");
  words.add("ground");
  words.add("host");
  words.add("improve");
  words.add("jam");
  words.add("kingdom");
  words.add("lack");
  words.add("maintain");
  words.add("never");
  words.add("object");
  words.add("presence");
  words.add("queue");
  words.add("receive");
  words.add("stuff");
  words.add("though");
  words.add("unlike");
  words.add("volume");
  words.add("write");
  words.add("xanthein");
  words.add("yarn");
  words.add("zinc");

  <11>
  words.add("apply");
  words.add("branch");
  words.add("company");
  words.add("decline");
  words.add("emerge");
  words.add("form");
  words.add("guard");
  words.add("however");
  words.add("invite");
  words.add("job");
  words.add("kill");
  words.add("line");
  words.add("move");
  words.add("number");
  words.add("operation");
  words.add("post");
  words.add("quotation");
  words.add("respect");
  words.add("secure");
  words.add("transfer");
  words.add("universe");
  words.add("various");
  words.add("wander");
  words.add("xeroradiograph");
  words.add("yoke");
  words.add("zigzag");

  <12>
  words.add("asia");
  words.add("beat");
  words.add("commit");
  words.add("doctor");
  words.add("expect");
  words.add("fine");
  words.add("generous");
  words.add("happy");
  words.add("impact");
  words.add("june");
  words.add("knife");
  words.add("leap");
  words.add("match");
  words.add("natural");
  words.add("own");
  words.add("prepare");
  words.add("quilt");
  words.add("relative");
  words.add("suspect");
  words.add("tell");
  words.add("useful");
  words.add("venture");
  words.add("whether");
  words.add("xerasia");
  words.add("yacht");
  words.add("zoology");

  <13>
  words.add("accesory");
  words.add("benefit");
  words.add("concern");
  words.add("delight");
  words.add("effort");
  words.add("force");
  words.add("grab");
  words.add("height");
  words.add("immediate");
  words.add("joke");
  words.add("kitchen");
  words.add("laugh");
  words.add("moment");
  words.add("next");
  words.add("occupy");
  words.add("patient");
  words.add("quest");
  words.add("represent");
  words.add("struggle");
  words.add("trip");
  words.add("unknown");
  words.add("valid");
  words.add("witness");
  words.add("xenotropic");
  words.add("yearly");
  words.add("zindabad");

  <14>
  words.add("apartment");
  words.add("back");
  words.add("complete");
  words.add("dna");
  words.add("effect");
  words.add("face");
  words.add("glow");
  words.add("hire");
  words.add("imply");
  words.add("july");
  words.add("knight");
  words.add("lend");
  words.add("mass");
  words.add("nail");
  words.add("official");
  words.add("purpose");
  words.add("quiz");
  words.add("reference");
  words.add("statement");
  words.add("term");
  words.add("upper");
  words.add("victim");
  words.add("within");
  words.add("xenate");
  words.add("youngster");
  words.add("zap");

  <15>
  words.add("available");
  words.add("behind");
  words.add("concrete");
  words.add("determine");
  words.add("escape");
  words.add("feed");
  words.add("guarantee");
  words.add("hate");
  words.add("inform");
  words.add("jacket");
  words.add("kiss");
  words.add("land");
  words.add("most");
  words.add("nothing");
  words.add("offend");
  words.add("pretend");
  words.add("quill");
  words.add("regard");
  words.add("show");
  words.add("trade");
  words.add("understand");
  words.add("vegetable");
  words.add("without");
  words.add("xiphoid");
  words.add("yew");
  words.add("zing");

  <16>
  words.add("agree");
  words.add("below");
  words.add("create");
  words.add("doubt");
  words.add("easy");
  words.add("forward");
  words.add("generation");
  words.add("hope");
  words.add("idnetify");
  words.add("jelly");
  words.add("kite");
  words.add("loud");
  words.add("major");
  words.add("nice");
  words.add("only");
  words.add("property");
  words.add("quench");
  words.add("rather");
  words.add("stand");
  words.add("trust");
  words.add("uncomfortable");
  words.add("vast");
  words.add("weather");
  words.add("xerophthalmia");
  words.add("yeoman");
  words.add("zealot");

  <17>
  words.add("appreciate");
  words.add("best");
  words.add("corn");
  words.add("different");
  words.add("entry");
  words.add("follow");
  words.add("gear");
  words.add("habit");
  words.add("iron");
  words.add("jolt");
  words.add("keyboard");
  words.add("learn");
  words.add("moral");
  words.add("numerous");
  words.add("odd");
  words.add("past");
  words.add("queer");
  words.add("read");
  words.add("severe");
  words.add("severe");
  words.add("undo");
  words.add("voice");
  words.add("waste");
  words.add("xystus");
  words.add("yummy");
  words.add("zippy");

  <18>
  words.add("attack");
  words.add("better");
  words.add("card");
  words.add("design");
  words.add("earth");
  words.add("fail");
  words.add("government");
  words.add("health");
  words.add("inportant");
  words.add("jail");
  words.add("kettle");
  words.add("lift");
  words.add("million");
  words.add("neat");
  words.add("ordinary");
  words.add("proceed");
  words.add("quail");
  words.add("reach");
  words.add("see");
  words.add("tackle");
  words.add("ugly");
  words.add("vocabulary");
  words.add("wet");
  words.add("xanthic");
  words.add("you");
  words.add("zillion");

  <19>
  words.add("admin");
  words.add("bus");
  words.add("car");
  words.add("dirt");
  words.add("enum");
  words.add("flower");
  words.add("gun");
  words.add("humble");
  words.add("image");
  words.add("juice");
  words.add("king");
  words.add("large");
  words.add("melon");
  words.add("normal");
  words.add("optical");
  words.add("power");
  words.add("quite");
  words.add("relax");
  words.add("super");
  words.add("tiger");
  words.add("umbrella");
  words.add("victory");
  words.add("world");
  words.add("xylophone");
  words.add("youtube");
  words.add("zebra");

  <20>
  words.add("alternative");
  words.add("both");
  words.add("challenge");
  words.add("daddy");
  words.add("egg");
  words.add("fill");
  words.add("green");
  words.add("hike");
  words.add("interstella");
  words.add("job");
  words.add("korea");
  words.add("like");
  words.add("metro");
  words.add("notice");
  words.add("outgoing");
  words.add("perfect");
  words.add("qnack");
  words.add("revolution");
  words.add("support");
  words.add("turn");
  words.add("united");
  words.add("violate");
  words.add("wraith");
  words.add("xylitol");
  words.add("yonne");
  words.add("zombie");

























}
